### ISSUE TITLE
我报错了啊，我用的win系统。

### ISSUE THREAD

**Issue by tandaishi** [wildabc/cmdwechat#1]
PS D:\Download\cmdwechat\cmdwechat-main> python.exe .\wechat.py
使用方法：
    回车直接发送消息
    用“@fil@example.pdf”发送名为“example.pdf”的文件
    类似地用“@img@”发送图片、“@vid@”发送视频
    _to 好友名：更换聊天好友
    _update：更新好友列表
    _exit：退出

Start auto replying.
Exception in thread Thread-3 (cmdloop):
Traceback (most recent call last):
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Download\cmdwechat\cmdwechat-main\wechat.py", line 113, in cmdloop
    line = session.prompt(self.to+'>', completer=self.completer)
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1034, in prompt
    return self.app.run(
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application\application.py", line 978, in run
    return loop.run_until_complete(
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application\application.py", line 885, in run_async
    return await _run_async(f)
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\application\application.py", line 737, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\input\win32.py", line 672, in attach_win32_input
    win32_handles.add_win32_handle(handle, callback)
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\input\win32.py", line 630, in add_win32_handle
    run_in_executor_with_context(wait, loop=loop)
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\eventloop\utils.py", line 36, in run_in_executor_with_context
    return loop.run_in_executor(None, ctx.run, func, *args)
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 816, in run_in_executor
    executor = concurrent.futures.ThreadPoolExecutor(
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\__init__.py", line 49, in __getattr__
    from .thread import ThreadPoolExecutor as te
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 37, in <module>
    threading._register_atexit(_python_exit)
  File "C:\Users\tan\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1504, in _register_atexit
    raise RuntimeError("can't register atexit after shutdown")
RuntimeError: can't register atexit after shutdown

**Comment by wildabc** [comment]
@tlf1144375711 我在网上搜了一下，好像都是Python 3.9以后的版本会抛这个错误。我用的是3.8，不知是不是这个原因。你在113行加上选项`complete_in_thread=True`试试，看有没有效果。
